general_cfg:
  algo_name: DDPG
  device: cpu
  env_name: BipedalWalker-v3
  eval_eps: 10
  eval_per_episode: 5
  load_checkpoint: true
  load_path: Train_BipedalWalker-v3_DDPG_20230414-214211
  max_steps: 900
  mode: test
  mp_backend: mp
  n_workers: 1
  new_step_api: true
  render: true
  render_mode: rgb_array
  save_fig: true
  seed: 2023
  show_fig: false
  test_eps: 3
  train_eps: 2000
  wrapper: null
algo_cfg:
  actor_hidden_dim: 128
  actor_lr: 5.0e-05
  batch_size: 256
  buffer_size: 20480
  critic_hidden_dim: 128
  critic_lr: 0.001
  gamma: 0.99
  tau: 0.01
