general_cfg:
  algo_name: PER_DQN
  device: cpu
  env_name: gym
  eval_eps: 10
  eval_per_episode: 5
  load_checkpoint: true
  load_path: Train_gym_PER_DQN_20230415-215002
  max_steps: 200
  mode: test
  mp_backend: mp
  n_workers: 1
  new_step_api: true
  render: false
  render_mode: human
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 200
  wrapper: null
algo_cfg:
  batch_size: 64
  buffer_size: 100000
  epsilon_decay: 500
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.99
  hidden_dim: 256
  lr: 0.0001
  per_alpha: 0.6
  per_beta: 0.4
  per_beta_annealing: 0.001
  per_epsilon: 0.01
  target_update: 4
  value_layers:
  - activation: relu
    layer_dim:
    - n_states
    - 256
    layer_type: linear
  - activation: relu
    layer_dim:
    - 256
    - 256
    layer_type: linear
  - activation: none
    layer_dim:
    - 256
    - n_actions
    layer_type: linear
env_cfg:
  id: CartPole-v1
  new_step_api: true
  render_mode: null
