general_cfg:
  algo_name: DQN
  device: cpu
  env_name: gym
  mode: test
  n_workers: 1
  load_checkpoint: true
  load_path: Train_MountainCar-v0_DQN_20230424-201738
  max_steps: 200
  save_fig: true
  seed: 3
  show_fig: false
  test_eps: 20
  train_eps: 200
  eval_eps: 10
  eval_per_episode: 5
  render: true
algo_cfg:
  value_layers:
    - layer_type: linear
      layer_dim: [256]
      activation: relu
    - layer_type: linear
      layer_dim: [256]
      activation: relu
  buffer_type: REPLAY_QUE
  buffer_size: 40000
  batch_size: 64
  epsilon_decay: 800
  epsilon_end: 0.01
  epsilon_start: 0.99
  gamma: 0.99
  lr: 0.01
  target_update: 4
env_cfg:
  id: MountainCar-v0
  new_step_api: true
  render_mode: rgb_array
  wrapper: null