general_cfg:
  algo_name: NoisyDQN
  device: cpu
  env_name: gym
  eval_eps: 10
  eval_per_episode: 5
  load_checkpoint: false
  load_path: Train_CartPole-v1_NoisyDQN
  max_steps: 200
  mode: train
  mp_backend: mp
  n_workers: 2
  new_step_api: true
  render: false
  render_mode: human
  save_fig: true
  seed: 1
  show_fig: false
  test_eps: 10
  train_eps: 200
  wrapper: null
algo_cfg:
  batch_size: 64
  buffer_size: 100000
  epsilon_decay: 500
  epsilon_end: 0.01
  epsilon_start: 0.95
  gamma: 0.95
  hidden_dim: 256
  lr: 0.0001
  target_update: 4
  tau: 1.0
env_cfg:
  id: CartPole-v1
  new_step_api: true
  render_mode: null
